### ISSUE TITLE
Project build error: Unresolveable build extension: plugin org.apache.maven.wago : prospect-addressvalidation

### ISSUE THREAD

**Issue by waqaskhan137** [temenostech/Prospect-IRIS#2]
I have just downloaded the project and imported in Design Studio and getting these errors

Offline / Missing artifact com.temenos.interaction:interaction-commands-odata:jar:0.8.0-SNAPSHOT

Offline / Missing artifact com.temenos.interaction:interaction-core:jar:0.8.0-SNAPSHOT

Project build error: Unresolveable build extension: Plugin org.apache.maven.wagon:wagon-ssh-external:2.9 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven.wagon:wagon-ssh-external:jar:2.9, org.codehaus.plexus:plexus-utils:jar:1.1: Cannot access central (http://repo1.maven.org/maven2) in offline mode and the artifact org.apache.maven.wagon:wagon-ssh-external:jar:2.9 has not been downloaded from it before.

**Comment by aphethean** [comment]
Apologies.  We need to update the versions to be the latest release versions (these are to be published in maven central, but I don't think they are yet).  I'll keep the issue open until they are.

**Comment by aphethean** [comment]
If you have DesignStudio you will actually have the latest version 0.8.0  - so just need to update the pom.xml's and you are away.

**Comment by mjangid** [comment]
IRIS & other technology version upgraded and binaries are included with design studio. Its working now.
