### ISSUE TITLE
Errors(13 items) Warnings(11 items)

### ISSUE THREAD

**Issue by waqaskhan137** [temenostech/Prospect-IRIS#3]
**Errors**
Description Resource    Path    Location    Type
Offline / Missing artifact com.temenos.interaction:interaction-commands-odata:jar:0.8.0-SNAPSHOT    pom.xml /prospect-addressvalidation line 41 Maven Dependency Problem
Offline / Missing artifact com.temenos.interaction:interaction-core:jar:0.8.0-SNAPSHOT  pom.xml /prospect-addressvalidation line 36 Maven Dependency Problem
Project build error: Non-resolvable parent POM for com.temenos.examples:testds:1.0-SNAPSHOT: Cannot access central (http://repo1.maven.org/maven2) in offline mode and the artifact com.temenos.maven:t24-core:pom:2015.9.0-SNAPSHOT has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM    pom.xml /Prospect-iris  line 1  Maven pom Loading Problem
Project build error: Non-resolvable parent POM for com.temenos.examples:testds:1.0-SNAPSHOT: Cannot access central (http://repo1.maven.org/maven2) in offline mode and the artifact com.temenos.maven:t24-core:pom:2015.9.0-SNAPSHOT has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM    pom.xml /Prospect-models-gen    line 1  Maven pom Loading Problem
Project build error: Non-resolvable parent POM: Cannot access central (http://repo1.maven.org/maven2) in offline mode and the artifact com.temenos.maven:t24-core:pom:2015.9.0-SNAPSHOT has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM pom.xml /Prospect-iris-parent   line 5  Maven pom Loading Problem
Project build error: Non-resolvable parent POM: Cannot access central (http://repo1.maven.org/maven2) in offline mode and the artifact com.temenos.maven:t24-core:pom:2015.9.0-SNAPSHOT has not been downloaded from it before. and 'parent.relativePath' points at wrong local POM pom.xml /Prospect-models    line 7  Maven pom Loading Problem
Project build error: Unresolveable build extension: Plugin org.apache.maven.wagon:wagon-ssh-external:2.9 or one of its dependencies could not be resolved: The following artifacts could not be resolved: org.apache.maven.wagon:wagon-ssh-external:jar:2.9, org.codehaus.plexus:plexus-utils:jar:1.1: Cannot access central (http://repo1.maven.org/maven2) in offline mode and the artifact org.apache.maven.wagon:wagon-ssh-external:jar:2.9 has not been downloaded from it before. pom.xml /prospect-addressvalidation line 1  Maven pom Loading Problem
The container 'Maven Dependencies' references non existing library 'C:\Users\Rana\Desktop\Temenos\design studio\t24-binaries\com\temenos\interaction\interaction-core\0.8.0-SNAPSHOT\interaction-core-0.8.0-SNAPSHOT.jar'   prospect-addressvalidation      Build path  Build Path Problem
The project cannot be built until build path errors are resolved    prospect-addressvalidation      Unknown Java Problem
The project was not built since its build path is incomplete. Cannot find the class file for org.apache.commons.httpclient.HttpClient. Fix the build path then try building this project    Prospect-iris       Unknown Java Problem
The superclass "javax.servlet.http.HttpServlet" was not found on the Java Build Path    index.jsp   /Prospect-iris/src/main/webappConfig/tafj   line 1  JSP Problem
The superclass "javax.servlet.http.HttpServlet" was not found on the Java Build Path    index.jsp   /Prospect-iris/src/main/webappConfig/tafj-jboss5    line 1  JSP Problem
The type org.apache.commons.httpclient.HttpClient cannot be resolved. It is indirectly referenced from required .class files    TestPOAITCase.java  /Prospect-iris/src/test/java/com/temenos/demo   line 1  Java Problem
**Warnings**
Description Resource    Path    Location    Type
Build path specifies execution environment J2SE-1.5. There are no JREs installed in the workspace that are strictly compatible with this environment.   prospect-addressvalidation      Build path  JRE System Library Problem
CheckStyle is not activated on this project!    Prospect-iris       Unknown Java Project Configuration Problem
CheckStyle is not activated on this project!    Prospect-models     Unknown Java Project Configuration Problem
CheckStyle is not activated on this project!    prospect-addressvalidation      Unknown Java Project Configuration Problem
FindBugs is not activated on this project!  Prospect-iris       Unknown Java Project Configuration Problem
FindBugs is not activated on this project!  Prospect-models     Unknown Java Project Configuration Problem
FindBugs is not activated on this project!  prospect-addressvalidation      Unknown Java Project Configuration Problem
No grammar constraints (DTD or XML Schema) referenced in the document.  jboss-deployment-structure.xml  /Prospect-iris/src/main/webappConfig/tafj/WEB-INF   line 1  XML Problem
No grammar constraints (DTD or XML Schema) referenced in the document.  jboss-web.xml   /Prospect-iris/src/main/webappConfig/tafj-jboss5/WEB-INF    line 1  XML Problem
No grammar constraints (DTD or XML Schema) referenced in the document.  jboss-web.xml   /Prospect-iris/src/main/webappConfig/tafj/WEB-INF   line 1  XML Problem
No grammar constraints (DTD or XML Schema) referenced in the document.  logback.xml /Prospect-iris/src/main/resources   line 1  XML Problem

**Comment by aphethean** [comment]
Duplicate https://github.com/temenostech/Prospect-IRIS/issues/2

**Comment by eden249** [comment]
how can i get other tafj projects?
