### ISSUE TITLE
Proper Getting started guide ? 

### ISSUE THREAD

**Issue by waqaskhan137** [temenostech/Prospect-IRIS#5]
I am trying to follow the videos and readme files but these are not written clear and easy to follow. What videos and readme says doesnt happen on my side as smooth as it is mentioned. 
Kindly provide some getting started guide and clear instructions.

**Comment by aphethean** [comment]
Coming soon.  thx for your interest.

**Comment by mjangid** [comment]
Now this will available in Dev Portal
